### ISSUE TITLE
mfc client call SocketError

### ISSUE THREAD

**Issue by alphabr** [KradekMFC/ModelsOnline#1]
Hi,
Im trying to use ModelsOnline, but this call to MFCClient SocketError dont exist  :+1: 
mfc.SocketError += (object s, SocketErrorEventArgs e) =>
                {
                    socketError = e.Exception;
                };

Thanks

**Comment by KradekMFC** [comment]
Apologies, I hadn't updated my code for the .net client on GitHub. I pushed that up today; grab the new version and see if that doesn't solve your problem.

**Comment by alphabr** [comment]
Thanks for the fast reply.

Now its working!

Thanks a lot!

**Comment by KradekMFC** [comment]
You're welcome.
